In [30]:
import pandas as pd

TARGET_PATH = 'data/data1.csv'

origin = pd.read_csv(TARGET_PATH, encoding='euc-kr')
origin

,선박청코드항명,연도,월,분기,외내항구분,수출입구분,선종명,시설명,부두구분명,톤코드명,국가,톤코드,국내선박수,국내선박톤수,외국선박수,외국선박톤수,전체선박수,전체선박톤수
0,신항,2024,7,3,내항,입항,기타선,신항2부두,컨테이너부두,100 - 500톤미만,아국선,2,1,200,0,0.0,1,200
1,북항,2024,7,3,내항,입항,기타선,A 박지,일반부두,100 - 500톤미만,아국선,2,1,322,0,0.0,1,322
2,신항,2024,7,3,외항,입항,풀 컨테이너선,신항7부두,컨테이너부두,"25,000-30,000톤미만",외국선,11,0,0,1,27968.0,1,27968
3,감천,2024,8,3,외항,입항,어선,동성실업부두,일반부두,"500 - 1,000톤미만",외국선,3,0,0,3,2318.0,3,2318
4,북항,2024,6,2,외항,입항,원유 운반선,남외항 박지,일반부두,"60,000-75,000톤미만",외국선,14,0,0,1,63294.0,1,63294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13790,신항,2024,5,2,외항,출항,풀 컨테이너선,신항3부두,컨테이너부두,"75,000-100,000톤미만",아국선,15,2,150122,0,0.0,2,150122
13791,북항,2024,6,2,내항,출항,LPG.LNG 운반선,남외항 박지,일반부두,"500 - 1,000톤미만",아국선,3,3,2995,0,0.0,3,2995
13792,감천,2024,5,2,내항,출항,석유정제품 운반선,동성실업부두,일반부두,100 - 500톤미만,아국선,2,2,505,0,0.0,2,505
13793,신항,2024,6,2,외항,출항,풀 컨테이너선,신항5부두,컨테이너부두,"30,000-50,000톤미만",외국선,12,0,0,6,249718.0,6,249718
13794,신항,2024,2,1,내항,출항,석유정제품 운반선,신항4부두,컨테이너부두,"500 - 1,000톤미만",아국선,3,5,4523,0,0.0,5,4523

In [31]:
origin.head()

,선박청코드항명,연도,월,분기,외내항구분,수출입구분,선종명,시설명,부두구분명,톤코드명,국가,톤코드,국내선박수,국내선박톤수,외국선박수,외국선박톤수,전체선박수,전체선박톤수
0,신항,2024,7,3,내항,입항,기타선,신항2부두,컨테이너부두,100 - 500톤미만,아국선,2,1,200,0,0.0,1,200
1,북항,2024,7,3,내항,입항,기타선,A 박지,일반부두,100 - 500톤미만,아국선,2,1,322,0,0.0,1,322
2,신항,2024,7,3,외항,입항,풀 컨테이너선,신항7부두,컨테이너부두,"25,000-30,000톤미만",외국선,11,0,0,1,27968.0,1,27968
3,감천,2024,8,3,외항,입항,어선,동성실업부두,일반부두,"500 - 1,000톤미만",외국선,3,0,0,3,2318.0,3,2318
4,북항,2024,6,2,외항,입항,원유 운반선,남외항 박지,일반부두,"60,000-75,000톤미만",외국선,14,0,0,1,63294.0,1,63294

In [32]:
origin.shape

(13795, 18)

In [33]:
origin.info()

<class 'pandas.DataFrame'>
RangeIndex: 13795 entries, 0 to 13794
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   선박청코드항명  13795 non-null  str
 1   연도       13795 non-null  int64
 2   월        13795 non-null  int64
 3   분기       13795 non-null  int64
 4   외내항구분    13795 non-null  str
 5   수출입구분    13795 non-null  str
 6   선종명      13795 non-null  str
 7   시설명      13767 non-null  str
 8   부두구분명    13767 non-null  str
 9   톤코드명     13795 non-null  str
 10  국가       13795 non-null  str
 11  톤코드      13795 non-null  int64
 12  국내선박수    13795 non-null  int64
 13  국내선박톤수   13795 non-null  int64
 14  외국선박수    13795 non-null  int64
 15  외국선박톤수   13777 non-null  float64
 16  전체선박수    13795 non-null  int64
 17  전체선박톤수   13795 non-null  int64
dtypes: float64(1), int64(9), str(8)
memory usage: 1.9 MB

In [34]:
origin.columns.to_list()

['선박청코드항명',
 '연도',
 '월',
 '분기',
 '외내항구분',
 '수출입구분',
 '선종명',
 '시설명',
 '부두구분명',
 '톤코드명',
 '국가',
 '톤코드',
 '국내선박수',
 '국내선박톤수',
 '외국선박수',
 '외국선박톤수',
 '전체선박수',
 '전체선박톤수']

In [35]:
beta = origin.copy()

In [36]:
# 월, 수출입구분 '입항', 선종명만 추출
beta_visit = beta[
    beta['수출입구분'] == '입항'
][['월', '선종명', '전체선박수']].copy()

beta_visit

       월          선종명  전체선박수
0      7          기타선      1
1      7          기타선      1
2      7      풀 컨테이너선      1
3      8           어선      3
4      6       원유 운반선      1
...   ..          ...    ...
13724  9        일반화물선      5
13725  9       원유 운반선      3
13726  9      시멘트 운반선      3
13727  9           어선      3
13728  8  LPG.LNG 운반선      2

[6860 rows x 3 columns]

In [37]:
ship_rank = (
    beta_visit
    .groupby(['월', '선종명'], as_index=False)['전체선박수']
    .sum()
)

ship_rank = ship_rank.sort_values(
    by=['월', '전체선박수'],
    ascending=[True, False]
)

ship_rank = ship_rank.reset_index(drop=True)

ship_rank

      월          선종명  전체선박수
0     1      풀 컨테이너선   1120
1     1    석유정제품 운반선   1081
2     1          기타선    655
3     1        일반화물선    246
4     1          산물선    173
..   ..          ...    ...
163  12     쎄미 컨테이너선     30
164  12      자동차 운반선     20
165  12      시멘트 운반선     16
166  12       원유 운반선     15
167  12  LPG.LNG 운반선     11

[168 rows x 3 columns]

In [39]:
# 1. 선종별 입항 비중

ship_share = (
    beta_visit
    .groupby('선종명', as_index=False)['전체선박수']
    .sum()
)
ship_share

            선종명  전체선박수
0   LPG.LNG 운반선    171
1           기타선   7658
2        냉동.냉장선    832
3           산물선   1835
4     석유정제품 운반선  11955
5       시멘트 운반선    308
6      쎄미 컨테이너선    413
7            어선   1247
8           여객선   1886
9        원유 운반선    292
10        일반화물선   2579
11      자동차 운반선    203
12      케미칼 운반선    495
13      풀 컨테이너선  12831

In [41]:
total_ships = ship_share['전체선박수'].sum()
total_ships

np.int64(42705)

In [43]:
ship_share['입항비중(%)'] = (
    ship_share['전체선박수']
    / total_ships
    * 100
).round(2)
ship_share

"""
선종별 입항 비중
= 해당 선종 입항 선박 수
  ÷ 전체 입항 선박 수
  × 100
"""

            선종명  전체선박수  입항비중(%)
0   LPG.LNG 운반선    171     0.40
1           기타선   7658    17.93
2        냉동.냉장선    832     1.95
3           산물선   1835     4.30
4     석유정제품 운반선  11955    27.99
5       시멘트 운반선    308     0.72
6      쎄미 컨테이너선    413     0.97
7            어선   1247     2.92
8           여객선   1886     4.42
9        원유 운반선    292     0.68
10        일반화물선   2579     6.04
11      자동차 운반선    203     0.48
12      케미칼 운반선    495     1.16
13      풀 컨테이너선  12831    30.05

In [44]:
# 2. 월별 입항 선박 수

monthly_visit = (
    beta_visit
    .groupby('월', as_index=False)['전체선박수']
    .sum()
)
monthly_visit

     월  전체선박수
0    1   3738
1    2   3240
2    3   3673
3    4   3711
4    5   3713
5    6   3607
6    7   3716
7    8   3609
8    9   3439
9   10   3709
10  11   3485
11  12   3065

In [46]:
monthly_visit = monthly_visit.sort_values(
    by='월'
).reset_index(drop=True)

monthly_visit

     월  전체선박수
0    1   3738
1    2   3240
2    3   3673
3    4   3711
4    5   3713
5    6   3607
6    7   3716
7    8   3609
8    9   3439
9   10   3709
10  11   3485
11  12   3065

In [47]:
# 3. 전월 대비 입항량 증감율

monthly_visit['전월대비증감률(%)'] = (
    monthly_visit['전체선박수']
    .pct_change()
    * 100
).round(2)

monthly_visit

     월  전체선박수  전월대비증감률(%)
0    1   3738         NaN
1    2   3240      -13.32
2    3   3673       13.36
3    4   3711        1.03
4    5   3713        0.05
5    6   3607       -2.85
6    7   3716        3.02
7    8   3609       -2.88
8    9   3439       -4.71
9   10   3709        7.85
10  11   3485       -6.04
11  12   3065      -12.05

In [48]:
# 4. 총 입항 선박수

total_visit = beta_visit['전체선박수'].sum()
total_visit

np.int64(42705)

In [50]:
import plotly.express as px